build:
	gcc -std=c99 -Wall -Werror -c arvore-binaria.c
	gcc -std=c99 -Wall -Werror -c main.c
	gcc main.o arvore-binaria.o -lm -o arvore-binaria

run:
	./arvore-binaria

clean:
	rm *.o
	rm arvore-binaria