build:
	gcc -std=c99 -Wall -Werror -c listacircular.c
	gcc -std=c99 -Wall -Werror -c aula13.c
	gcc aula13.o listacircular.o -lm -o listacircular

run:
	./listacircular

clean:
	rm *.o
	rm listacircular